# Generated by Django 4.1.7 on 2023-03-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(max_length=50)),
                ('pic', models.FileField(blank=True, default='avtar.jpg', null=True, upload_to='seller_profile_pic')),
            ],
        ),
    ]
