# Generated by Django 4.1.7 on 2023-04-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('m', 'men'), ('w', 'women'), ('s', 'shoes'), ('w', 'watch'), ('b', 'bag')], max_length=1, null=True),
        ),
    ]
