# Generated by Django 4.1.7 on 2023-04-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('women', 'women'), ('shoes', 'shoes'), ('watch', 'watch'), ('bag', 'bag')], max_length=5, null=True),
        ),
    ]
