# Generated by Django 4.1.7 on 2023-04-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_myorders_orderedproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedProducts',
        ),
    ]
