# Generated by Django 4.1.7 on 2023-04-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
