# Generated by Django 4.1.7 on 2023-04-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_alter_wishlist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='seller',
        ),
    ]
