# Generated by Django 4.1.7 on 2023-04-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_remove_wishlist_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
