# Generated by Django 4.1.7 on 2023-04-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_product_category'),
        ('buyer', '0011_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('buyer', 'product')},
        ),
    ]
